### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by virtualtam** [shaarli/netscape-bookmark-parser#28]
### Goal
- provide a Debian package to enable packaging Shaarli > 0.8

### TODO
- this repo:
    - [x] #27 keep Composer metadata
    - [x] add a CHANGELOG.md
- [ ] create/register a Debian package/project
    - [ ] add Debian-specific metadata
    - [ ] automate metadata generation (copyright, changelog, etc.)

### Resources
Meta:
- http://keepachangelog.com/en/0.3.0/

Shaarli package:
- https://packages.debian.org/sid/shaarli
- https://wiki.debian.org/FreedomBox/Manual

Debian packaging:
- https://www.debian.org/doc/devel-manuals#packaging-tutorial
- https://www.debian.org/doc/debian-policy/
- https://www.debian.org/doc/manuals/developers-reference/
- https://wiki.debian.org/PackagingWithGit
- https://wiki.debian.org/HowToPackageForDebian
- https://feeding.cloud.geek.nz/posts/whats-in-a-debian-directory/

Debian tools for PHP packaging:
- https://packages.debian.org/sid/pkg-php-tools
- https://sources.debian.net/src/pkg-php-tools/1.34/debian/README.Composer/
- https://wiki.debian.org/ReleaseGoals/pkg-php-tools

Debian CI:
- https://ci.debian.net/
- https://ci.debian.net/doc/file.MAINTAINERS.html
- https://ci.debian.net/doc/file.TUTORIAL.html

**Comment by virtualtam** [comment]
Closing due to lack of time and interest, feel free to reopen / submit a PR :)
